import { PRIVACY_ARTICLE_INDEX } from "./privacyPosts";

/** Canonical pillar for “effective rate vs 2.9%” intent (replaces legacy /blog/… URL). */
export const PILLAR_EFFECTIVE_RATE_PATH = "/why-stripe-fee-rate-higher-than-2-9";

export type BlogIndexEntry = {
  slug: string;
  path: string;
  title: string;
  desc: string;
  time: string;
  publishedAt: string;
  updatedAt: string;
  sitemapPriority: number;
};

/** Fee / optimization articles under /blog/* (static page.tsx per slug). */
export const FEE_BLOG_ENTRIES: BlogIndexEntry[] = [
  {
    slug: "how-i-found-1400-in-hidden-stripe-fees",
    path: "/blog/how-i-found-1400-in-hidden-stripe-fees",
    title: "How I Found ~$1,400/Year in Hidden Stripe Fee Opportunities",
    desc: "A real Balance CSV case study: $3,597.77 in fees, 3.82% processing rate, 4.02% all-in cost, and the drivers worth checking.",
    time: "6 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.8,
  },
  {
    slug: "cross-border-stripe-fees-migration-2026",
    path: "/blog/cross-border-stripe-fees-migration-2026",
    title: "Cross-Border Stripe Fees & Global Migration (June 2026)",
    desc: "Why record global mobility and remote-work visas can push Stripe effective rates from ~2.9% toward 5%+ — and what to monitor in your CSV.",
    time: "10 min",
    publishedAt: "2026-06-22",
    updatedAt: "2026-06-22",
    sitemapPriority: 0.83,
  },
  {
    slug: "stripe-fee-audit-checklist-for-saas-founders",
    path: "/blog/stripe-fee-audit-checklist-for-saas-founders",
    title: "Stripe Fee Audit Checklist for SaaS Founders",
    desc: "A practical monthly Stripe fee audit checklist: effective rate, Balance CSV, international cards, refunds, small charges, and what to compare over time.",
    time: "8 min",
    publishedAt: "2026-05-25",
    updatedAt: "2026-05-25",
    sitemapPriority: 0.77,
  },
  {
    slug: "stripe-fee-leakage-report-may-2026",
    path: "/blog/stripe-fee-leakage-report-may-2026",
    title: "Stripe Fee Leakage Report: Who Is Safe?",
    desc: "A May 2026 diagnostic model for SaaS founders: which Stripe profiles stay near baseline and which quietly bleed margin.",
    time: "9 min",
    publishedAt: "2026-05-18",
    updatedAt: "2026-05-18",
    sitemapPriority: 0.76,
  },
  {
    slug: "stripe-alternatives-2026",
    path: "/blog/stripe-alternatives-2026",
    title: "Best Stripe Alternatives 2026: Fees & Use Cases",
    desc: "Compare eight Stripe alternatives for SaaS, ecommerce, POS, bank debit, global tax, enterprise payments, and lower processing costs.",
    time: "11 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-08-19",
    sitemapPriority: 0.78,
  },
  {
    slug: "stripe-credit-card-processing-fees",
    path: "/blog/stripe-credit-card-processing-fees",
    title: "Stripe Credit Card Processing Fees: Rates & Real Cost",
    desc: "Stripe credit card processing fees often start at 2.9% + $0.30 in the US. See examples, effective rates, extra costs, and audit steps.",
    time: "8 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-08-19",
    sitemapPriority: 0.76,
  },
  {
    slug: "stripe-vs-paypal-fees",
    path: "/blog/stripe-vs-paypal-fees",
    title: "Stripe vs PayPal Fees: Real Comparison",
    desc: "Compare published Stripe and PayPal fees, then learn why your actual payment cost depends on checkout mix, refunds, international customers, and average charge size.",
    time: "7 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.74,
  },
  {
    slug: "stripe-international-card-fees",
    path: "/blog/stripe-international-card-fees",
    title: "Stripe International Card Fees: Why Your Rate Is Higher",
    desc: "Stripe international card fees add ~1.5% on cross-border cards — a common reason effective rate and payout feel worse than 2.9%.",
    time: "6 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-07-19",
    sitemapPriority: 0.72,
  },
  {
    slug: "stripe-ach-vs-credit-card-fees",
    path: "/blog/stripe-ach-vs-credit-card-fees",
    title: "Stripe ACH vs Credit Card Fees: When ACH Saves Money",
    desc: "ACH usually beats standard domestic card pricing on cost. See the $5 cap math and when B2B SaaS should switch.",
    time: "7 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.72,
  },
  {
    slug: "stripe-fees-small-transactions",
    path: "/blog/stripe-fees-small-transactions",
    title: "Stripe Fees for Small Transactions: Why Your Rate Is Higher",
    desc: "The fixed $0.30 Stripe fee dominates micro-transactions. See why $5-$10 charges show inflated effective rates and how a Balance CSV surfaces the drag.",
    time: "5 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.71,
  },
  {
    slug: "stripe-blended-rate-calculator",
    path: "/blog/stripe-blended-rate-calculator",
    title: "Stripe Blended Rate Calculator: Find Your True Fee Rate",
    desc: "Formula for blended rate, what pushes it above 2.9%, and how to verify from your CSV.",
    time: "6 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-07-19",
    sitemapPriority: 0.71,
  },
  {
    slug: "how-to-export-stripe-balance-csv",
    path: "/blog/how-to-export-stripe-balance-csv",
    title: "How to Export Stripe Balance CSV: Step-by-Step Guide",
    desc: "Step-by-step: export the Itemized Stripe Balance CSV (not Summary), get the right columns, and check your real fee rate.",
    time: "4 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-07-19",
    sitemapPriority: 0.73,
  },
  {
    slug: "why-stripe-effective-rate-jumped-this-month",
    path: "/blog/why-stripe-effective-rate-jumped-this-month",
    title: "Why Did My Stripe Effective Rate Jump This Month?",
    desc: "6 specific causes — international cards, new low-priced products, refunds, FX stacking — and how to diagnose each from your CSV.",
    time: "8 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.78,
  },
  {
    slug: "why-stripe-fees-increase",
    path: "/blog/why-stripe-fees-increase",
    title: "Why Did My Stripe Fees Increase This Month?",
    desc: "Payout lower than expected or fees up vs last month? International cards, refund fees not returned, Radar/Billing, FX — plus a CSV checklist.",
    time: "5 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-07-19",
    sitemapPriority: 0.8,
  },
  {
    slug: "how-to-reduce-stripe-fees",
    path: "/blog/how-to-reduce-stripe-fees",
    title: "How to Reduce Your Stripe Fees",
    desc: "Practical tactics: custom pricing, ACH, fewer disputes.",
    time: "7 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.65,
  },
  {
    slug: "stripe-effective-fee-rate-explained",
    path: "/blog/stripe-effective-fee-rate-explained",
    title: "What Is Your Stripe Effective Fee Rate?",
    desc: "How to calculate it and what a healthy rate looks like.",
    time: "4 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.65,
  },
];

const privacyEntries: BlogIndexEntry[] = PRIVACY_ARTICLE_INDEX.map((post) => ({
  slug: post.slug,
  path: `/blog/${post.slug}`,
  title: post.title,
  desc: post.desc,
  time: post.time,
  publishedAt: post.datePublished,
  updatedAt: post.dateModified,
  sitemapPriority: 0.74,
}));

/** Blog hub list (privacy cluster + fee articles). Latest fee article pinned first. */
export const BLOG_HUB_POSTS: BlogIndexEntry[] = [
  FEE_BLOG_ENTRIES[0],
  ...privacyEntries,
  ...FEE_BLOG_ENTRIES.slice(1),
];

/** SEO landing pages outside /blog (included in sitemap). */
export const SEO_LANDING_ENTRIES: BlogIndexEntry[] = [
  {
    slug: "why-stripe-fee-rate-higher-than-2-9",
    path: PILLAR_EFFECTIVE_RATE_PATH,
    title: "Why Is My Stripe Effective Rate Higher Than Expected?",
    desc: "Effective rate and payout often run above 2.9% from international cards, refund fees not returned, FX, and small tickets.",
    time: "8 min",
    publishedAt: "2026-05-16",
    updatedAt: "2026-07-19",
    sitemapPriority: 0.85,
  },
  {
    slug: "stripe-fees-report",
    path: "/stripe-fees-report",
    title: "Stripe Fees Report: What to Include Beyond Dashboard Totals",
    desc: "Processing rate, all-in cost, refund drag, international uplift, and high-fee rows — from a Balance CSV export.",
    time: "4 min",
    publishedAt: "2026-08-10",
    updatedAt: "2026-08-10",
    sitemapPriority: 0.77,
  },
  {
    slug: "stripe-fee-calculator",
    path: "/stripe-fee-calculator",
    title: "Stripe Fee Calculator: Estimate Fees, Then Verify Your Real Rate",
    desc: "Free Stripe fee calculator for monthly volume, average charge size, and reverse fee math. Estimate costs, then verify your real rate from CSV.",
    time: "5 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-07-20",
    sitemapPriority: 0.8,
  },
  {
    slug: "what-percent-does-stripe-take",
    path: "/what-percent-does-stripe-take",
    title: "What Percentage Does Stripe Take? Fees Explained",
    desc: "See the Stripe percentage fee by transaction size, from the common US 2.9% + $0.30 price to your real blended rate from Balance CSV.",
    time: "4 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-08-19",
    sitemapPriority: 0.79,
  },
  {
    slug: "compare-stripe-paypal-wise",
    path: "/compare-stripe-paypal-wise",
    title: "Stripe vs PayPal vs Wise Fees: Compare Before Switching",
    desc: "Compare Stripe, PayPal, and Wise by payment use case, then audit your real Stripe baseline before moving checkout volume.",
    time: "6 min",
    publishedAt: "2026-06-26",
    updatedAt: "2026-06-26",
    sitemapPriority: 0.78,
  },
  {
    slug: "should-i-switch-from-stripe",
    path: "/should-i-switch-from-stripe",
    title: "Should I Switch From Stripe? Audit Fees First",
    desc: "Before switching from Stripe, audit whether the real driver is international cards, small charges, refunds, ACH opportunities, checkout conversion, or tax operations.",
    time: "7 min",
    publishedAt: "2026-07-13",
    updatedAt: "2026-07-13",
    sitemapPriority: 0.78,
  },
  {
    slug: "stripe-vs-square-fees",
    path: "/stripe-vs-square-fees",
    title: "Square vs Stripe Fees: Which Is Cheaper?",
    desc: "Square vs Stripe fees by use case (SaaS, POS, low-ticket). Audit your real Stripe rate before switching processors.",
    time: "6 min",
    publishedAt: "2026-07-13",
    updatedAt: "2026-07-16",
    sitemapPriority: 0.72,
  },
  {
    slug: "stripe-vs-gocardless",
    path: "/stripe-vs-gocardless",
    title: "Stripe vs GoCardless: Card Fees vs Bank Debit",
    desc: "Compare Stripe and GoCardless for recurring payments, ACH, SEPA, B2B invoices, card checkout, and when bank debit can reduce payment costs.",
    time: "6 min",
    publishedAt: "2026-07-13",
    updatedAt: "2026-07-13",
    sitemapPriority: 0.72,
  },
  {
    slug: "stripe-vs-paddle-fees",
    path: "/stripe-vs-paddle-fees",
    title: "Stripe vs Paddle Fees: Processor vs Merchant of Record",
    desc: "Compare Stripe and Paddle for SaaS: payment processing, merchant-of-record tax handling, international sales, checkout control, and what to audit before switching.",
    time: "6 min",
    publishedAt: "2026-07-13",
    updatedAt: "2026-07-13",
    sitemapPriority: 0.7,
  },
  {
    slug: "how-it-works",
    path: "/how-it-works",
    title: "How Stripe Fee Auditor Handles Your CSV",
    desc: "See exactly what happens when you upload a Stripe Balance CSV: server analysis, stored report data, retention, and core logic links.",
    time: "4 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-06-25",
    sitemapPriority: 0.68,
  },
  {
    slug: "stripe-data-export",
    path: "/stripe-data-export",
    title: "Export Stripe Data to CSV, JSON, Tableau, or PostgreSQL",
    desc: "Choose the right Stripe export path for JSON, Tableau, Power BI, PostgreSQL, or fee reconciliation from Balance CSV.",
    time: "5 min",
    publishedAt: "2026-07-20",
    updatedAt: "2026-07-20",
    sitemapPriority: 0.66,
  },
  {
    slug: "stripe-balance-csv",
    path: "/stripe-balance-csv",
    title: "Export Stripe Balance CSV & Transactions for Fee Audit",
    desc: "Export Stripe Balance transactions (itemized CSV) in ~5 minutes. Check effective rate, refund leakage, and international card mix.",
    time: "4 min",
    publishedAt: "2026-06-25",
    updatedAt: "2026-08-10",
    sitemapPriority: 0.7,
  },
];

export const LEGACY_BLOG_REDIRECTS = [
  {
    source: "/blog/why-stripe-effective-rate-higher-than-2-9-percent",
    destination: PILLAR_EFFECTIVE_RATE_PATH,
  },
] as const;
